postgres:
  ip_address: localhost
  port: 5432
  username: postgres
  password: postgres 
  db_name: personal_finance

statement_services:
  debit_stmt_input_dir: input_files/debit_statements
  credit_card_stmt_input_dir: input_files/credit_card_statements