postgres:
  ip_address: localhost
  port: 5432
  username: postgres
  password: postgres 
  db_name: personal_finance

statement_services:
  abn_debit_stmt:
    input_dir: input_files/debit_statements
    file_glob: "*.TAB"
  credit_card_stmt:
    input_dir: input_files/credit_card_statements
    file_glob: "Statement-*.pdf"
  bunq_stmt:
    input_dir: input_files/bunq_statements
    file_glob: "*.sta"